// generators/app/templates/demo.application/widgets/example/react-hello-world-widget/react-hello-world-widget.jsx
<%- banner %>
import React from 'react';

export const injections = [ 'axReactRender' ];
export function create( reactRender ) {

   const message  = 'Hello World!';

   return () => (
      <div className="panel panel-primary">
         <div className="panel-heading">
            <h3 className="panel-title">The <em>react-hello-world-widget</em> says ...</h3>
         </div>
         <div className="panel-body">
            <h1>{message}</h1>
         </div>
      </div>
   );
}

// generators/app/templates/demo.application/widgets/example/vue-hello-world-widget/vue-hello-world-widget.vue
<template>
   <div class="panel panel-primary">
      <div class="panel-heading">
         <h3 class="panel-title">The <em>vue-hello-world-widget</em> says ...</h3>
      </div>
      <div class="panel-body">
         <h1>{{ message }}</h1>
      </div>
   </div>
</template>

<script>
<%- banner %>
export default {
   data: () => ({ message: 'Hello World!' }),
   created() {
   }
};
</script>
